#%RAML 0.8
---
title: Rostering Application API
baseUri: http://rostering.api.net
version: v1



schemas:
  - shiftInformation: |
      {
        "type": "object",
        "$schema": "http://json-schema.org/draft-03/schema",
        "id": "http://jsonschema.net",
        "required": true,
        "properties": {
          "shiftId": {
            "type": "string",
            "required": "true",
            "minLength": 36,
            "maxLength": 36
          },
          "shiftType": {
            "type": "string",
            "required": true
          },
          "shiftTitle":{
            "type": "string",
            "required": true
          },
          "shiftStartDate": {
            "type": "string",
            "required": true
          },
          "shiftEndDate": {
            "type": "string",
            "required": true
          },
          "shiftStartTime": {
            "type": "string",
            "required": true
          },
          "shiftEndTime": {
            "type": "string",
            "required": true
          },
          "actualShiftStartTime": {
            "type": "string",
            "required": true
          },
          "actualShiftEndTime": {
            "type": "string",
            "required": true
          }

        }
      }
  - shiftListOfTask:  |
      {
        "type":"object",
        "$schema": "http://json-schema.org/draft-03/schema",
        "id": "http://jsonschema.net",
        "required": false,
        "properties": {
          "shiftId":  {
            "type": "string",
            "required": true,
            "minLength":  36,
            "maxLength":  36 
          },
          "taskStartTime": {
            "type": "string",
            "required": false
          },
          "taskEndTime": {
            "type": "string",
            "required": false
          },
          "actualStartTime": {
            "type": "string",
            "required": false
          },
          "actualEndTime": {
            "type": "string",
            "required": false
          },
          "createdby": {
            "type":"string",
            "required": true
          },
          "updatedby": {
            "type": "string",
            "required": false
          }
        }
      }
